name: Sjoerd Dijkstra
favicon: null
layout_spectrum: 0.61594
typography_spectrum: 0.42976
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C8C0A8'
    - '#6B1919'
    - '#5090A0'
    - '#D85858'
    - '#B8D8E0'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
