analytics: {}
color:
  brandColors:
    - '#C8C0A8'
    - '#6B1919'
    - '#5090A0'
    - '#D85858'
    - '#B8D8E0'
  brandStrength: 0.659539
  lightness: 0.499177
  rhythmicContrast: 0.699835
  saturation: 0.509868
cta: {}
layout_spectrum: 0.519736
name: sd
opengraph: {}
purpose: []
typography_spectrum: 0.216282
