typography_spectrum: 0.41909
color:
  brandColors:
    - '#271418'
    - '#d0dcd2'
    - '#d9532f'
    - '#378085'
    - '#9b9294'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.81765
analytics:
  google: null
  facebook: null
  twitter: null
name: Sjoerd Dijkstra
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: For the weak
purpose: []
